baseURL = "https://rajasimon.io/"
languageCode = "en-us"
title = "Raja Simon"
summaryLength = 40
assetDir = "static"
enableRobotsTXT = true

[build]
  writeStats = true

[author]
  name = "Raja Simon"
  homepage = "https://rajasimon.io"


[params]
    twitter = "rajasimon"
    django = "#0C4B33"
    python = "#0b538c"
    sql = "#044a64"
    google = "#4285F4"
    personal = "#FFFFFF"
    pymongo = "#0faa50"
    motor = "#8eadbf"
    javascript = "#ecdb54"
    postgresql = "#336690"
    hugo = "#c9177e"
