baseURL = "https://rajasimon.io/"
languageCode = "en-us"
title = "Raja Simon"

theme = "custombulma"
summaryLength = 40
paginate = 5
googleAnalytics = "UA-157573143-2"

[params]
    twitter = "rajasimon"
    django = "#0C4B33"
    python = "#4B8BBE"
    sql = "#044a64"
    google = "#4285F4"
    personal = "#FFFFFF"
    pymongo = "#0faa50"
    motor = "#8eadbf"